version: "3.9"

networks:
  nginx_proxy_net:
    driver: bridge

services:

  labyrinth:
    build: 
      context: ./laby
    container_name: labyrinthnavi
    networks:
      - nginx_proxy_net
    expose:
      - "${LABY_PORT}"
    environment:
      - LABY_PORT=${LABY_PORT}
      - TZ=Asia/Seoul

  nginxproxy:
    build: 
      context: ./nginxproxy
    container_name: reverseproxy
    volumes:
      - ./nginxproxy/logs:/var/log/nginx
    networks:
      - nginx_proxy_net
    depends_on:
      - labyrinth
    ports:
      - "3733:${LABY_PORT}/tcp"
    environment:
      - LABY_PORT=${LABY_PORT}
      - TZ=Asia/Seoul