version: "3.9"

networks:
  nginx_proxy_net:
    driver: bridge

services:

  labyrinth:
    build: 
      context: ./laby
    container_name: labyrinthnavi
    networks:
      - nginx_proxy_net
    expose:
      - "${LABY_PORT}"
    environment:
      - LABY_PORT=${LABY_PORT}
      - TZ=Asia/Seoul

  minecraft:
    build: 
      context: ./minecraft
    tty: true
    stdin_open: true
    container_name: minecraft
    volumes:
      - ./minecraft/server-data:/data
    networks:
      - nginx_proxy_net
    expose:
      - "${MINECRAFT_PORT}/tcp"
    environment:
      - MINECRAFT_PORT=${MINECRAFT_PORT}
      - EULA=TRUE
      - MAX_MEMORY=16G
      - TZ=Asia/Seoul


  nginxproxy:
    build: 
      context: ./nginxproxy
    container_name: reverseproxy
    volumes:
      - ./nginxproxy/logs:/var/log/nginx
    networks:
      - nginx_proxy_net
    ports:
      - "3733:${LABY_PORT}/tcp"
      - "${MINECRAFT_PORT}:${MINECRAFT_PORT}/tcp"
    environment:
      - LABY_PORT=${LABY_PORT}
      - MINECRAFT_PORT=${MINECRAFT_PORT}
      - TZ=Asia/Seoul