version: "3.9"

networks:
  nginx_proxy_net:
    driver: bridge

services:

  labyrinth:
    build: 
      context: ./laby
    container_name: labyrinthnavi
    networks:
      - nginx_proxy_net
    expose:
      - "${LABY_PORT}"
    environment:
      - LABY_PORT=${LABY_PORT}
      - TZ=Asia/Seoul

  corekeeper:
    build: 
      context: ./corekeeper
    container_name: corekeeper
    volumes:
    networks:
      - nginx_proxy_net
    expose:
      - "${COREKEEPER_PORT}/udp"


  nginxproxy:
    build: 
      context: ./nginxproxy
    container_name: reverseproxy
    volumes:
      - ./nginxproxy/logs:/var/log/nginx
    networks:
      - nginx_proxy_net
    depends_on:
      - corekeeper
    ports:
      - "3733:${LABY_PORT}/tcp"
      - "${COREKEEPER_PORT}:${COREKEEPER_PORT}/udp"
    environment:
      - LABY_PORT=${LABY_PORT}
      - COREKEEPER_PORT=${COREKEEPER_PORT}
      - TZ=Asia/Seoul